apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: mitose
  name: mitose
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: mitose
    spec:
      containers:
      - name: mitose
        image: hugobcar/mitose:latest
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: mitose
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: mitose
  type: ClusterIP
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mitose
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["config"]
  verbs: ["get", "watch", "list", "update"]

