apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: mitose
  name: mitose
  namespace: mitose
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mitose
  template:
    metadata:
      labels:
        run: mitose
    spec:
      containers:
      - name: mitose
        image: hugobcar/mitose:v0.0.1
        imagePullPolicy: Always
        env:
          - name: AWSKEY
            valueFrom:
              secretKeyRef:
                name: aws-mitose
                key: key
          - name: AWSSECRET
            valueFrom:
              secretKeyRef:
                name: aws-mitose
                key: secret
          - name: CONFIGMAP
            value: config
      restartPolicy: Always
      serviceAccount: mitose
      serviceAccountName: mitose
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mitose
  namespace: mitose
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mitose
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: mitose
  namespace: mitose